version: '3.5'

services:
  spotlight.en:
    image: dbpedia/dbpedia-spotlight
    container_name: dbpedia-spotlight.en
    volumes:
      - spotlight-model:/opt/spotlight/models
    restart: unless-stopped
    ports:
      - "0.0.0.0:2222:80"
    command: /bin/spotlight.sh en

volumes:
  spotlight-model:
    external: true
